networks:
  inception:

volumes:
  mariadb:
  wordpress:

services:
  wordpress:
    container_name: wordpress
    env_file: .env
    build:
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PWD: ${DB_PWD}
        WP_URL: ${WP_URL}
        WP_TITLE: ${WP_TITLE}
        WP_ADMIN_USR: ${WP_ADMIN_USR}
        WP_ADMIN_PWD: ${WP_ADMIN_PWD}
        WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      context: /Users/Axel/Desktop/Ecole_42/Inception/srcs/requirements/wordpress/.
      dockerfile: /Users/Axel/Desktop/Ecole_42/Inception/srcs/requirements/wordpress/Dockerfile
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - /Users/Axel/data_inception/wordpress:/var/www/html
    expose:
      - "9000"
  
  mariadb:
    container_name: mariadb
    env_file: .env
    build: 
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PWD: ${DB_PWD}
        DB_PWD_ROOT: ${DB_PWD_ROOT}
      context: /Users/Axel/Desktop/Ecole_42/Inception/srcs/requirements/mariadb/.
    networks:
      - inception
    volumes:
      - /Users/Axel/data_inception/mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    env_file: .env
    build:
      context: /Users/Axel/Desktop/Ecole_42/Inception/srcs/requirements/nginx/.
      dockerfile: /Users/Axel/Desktop/Ecole_42/Inception/srcs/requirements/nginx/Dockerfile
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: always

